### PR TITLE
Add uninstall

### PR DESCRIPTION
**Pull request by grabbou**

### CODE REVIEW

**Comment by Kureev** [comment]
Is it ready for review? LGTM so far 👍

**Comment by grabbou** [comment]
I think so :) (that missing ready for review label :D)

**Comment by Kureev** [comment]
Then merge it in and make a release 👍

**Comment by grabbou** [comment]
All right! Will do later today (maybe we get a chance to merge other PRs as well and do a big one)

**Comment by hassankhan** [comment]
Thanks guys!

**Pull request merged**
